#!/bin/bash

# Delete everything about a running Rucio application. Don't delete the networking stuff (i.e. Services)
echo '
                             _
                            | \
                           _|  \______________________________________
                          - ______        ________________          \_`,
                        -(_______            -=    -=        USAF       )
                                 `--------=============----------------`
                                           -   -
                                         -   -
                                         -   -
                                       -   -
                                       -   -
                                     -   -
                                   -   -
                                 -   -
                                 -   -
                               -   -
                               -   -
                             -   -
'
echo '
                             ____
                     __,-~~/~    `---.
                   _/_,---(      ,    )
               __ /        <    /   )  \___
- ------===;;;*====------------------===;;;===----- -  -
                  \/  ~"~"~"~"~"~\~"~)~"/
                  (_ (   \  (     >    \)
                   \_( _ <         >_>*
                      ~ `-i* ::>|--"
                          I;|.|.|
                         <|i::|i|`.
                        (` ^*"`-* ")
'

oc delete job --all && oc delete cronjob --all
oc get deployments | tail -n+2 | awk '{print $1}' | xargs -I {} oc delete deployment {} && \
oc get secrets | tail -n+2 | awk '{print $1}' | xargs -I {} oc delete secret {}
